### ISSUE TITLE
Sometimes local tests stop working unless pycache folders are cleaned

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#132]
This happened to me, I couldn't run the tests anymore, kept getting the following:

```
(venv) vagrant@vagrant:/vagrant$ make coverage
py.test --cov-report term-missing --cov lxdock
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.5/site-packages/_pytest/config.py", line 329, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/vagrant/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.5/site-packages/_pytest/config.py", line 360, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/vagrant/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/vagrant/venv/lib/python3.5/site-packages/_pytest/config.py", line 366, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/vagrant/venv/lib/python3.5/site-packages/py/_path/local.py", line 686, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
py._path.local.LocalPath.ImportMismatchError: ('tests.conftest', '/home/rob/Projects/lxdock/tests/conftest.py', local('/vagrant/tests/conftest.py'))
ERROR: could not load /vagrant/tests/conftest.py
```

What fixed it for me is clearning out the pycache folders (.pyc files).

Maybe make coverage should always be doing this, or at least there should be a "make clean" to do this.

**Comment by robvdl** [comment]
Seems to be a py.test issue, but the easy solution is to clean out the .pyc files.

https://github.com/pytest-dev/pytest/issues/2042
