### ISSUE TITLE
Recent variable substitution too fragile, please switch to jinja2

### ISSUE THREAD

**Issue by robvdl** [lxdock/lxdock#73]
Since upgrading from 0.2 to 0.2.1-dev, it's making my lxdock file crash.

$ lxdock destroy

<pre>
Traceback (most recent call last):
  File "/usr/bin/lxdock", line 11, in <module>
    load_entry_point('lxdock', 'console_scripts', 'lxdock')()
  File "/home/rob/Projects/lxdock/lxdock/cli/main.py", line 244, in main
    LXDock(argv=argv)
  File "/home/rob/Projects/lxdock/lxdock/cli/main.py", line 118, in __init__
    getattr(self, args.action)(args)
  File "/home/rob/Projects/lxdock/lxdock/cli/main.py", line 143, in destroy
    container_names = args.name or [c.name for c in self.project.containers]
  File "/home/rob/Projects/lxdock/lxdock/cli/main.py", line 221, in project
    self._project = get_project()
  File "/home/rob/Projects/lxdock/lxdock/cli/project.py", line 10, in get_project
    config = Config.from_base_dir(base_dir)
  File "/home/rob/Projects/lxdock/lxdock/conf/config.py", line 82, in from_base_dir
    config.interpolate()
  File "/home/rob/Projects/lxdock/lxdock/conf/config.py", line 116, in interpolate
    self._dict = interpolate_variables(self._dict, mapping)
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 23, in interpolate_variables
    return {k: interpolate(v) for k, v in config_dict.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 23, in <dictcomp>
    return {k: interpolate(v) for k, v in config_dict.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 20, in interpolate
    return [interpolate(v) for v in value]
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 20, in <listcomp>
    return [interpolate(v) for v in value]
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 18, in interpolate
    return {k: interpolate(v) for k, v in value.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 18, in <dictcomp>
    return {k: interpolate(v) for k, v in value.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 20, in interpolate
    return [interpolate(v) for v in value]
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 20, in <listcomp>
    return [interpolate(v) for v in value]
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 18, in interpolate
    return {k: interpolate(v) for k, v in value.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 18, in <dictcomp>
    return {k: interpolate(v) for k, v in value.items()}
  File "/home/rob/Projects/lxdock/lxdock/conf/interpolation.py", line 16, in interpolate
    return Template(value).substitute(**mapping)
  File "/usr/lib/python3.5/string.py", line 129, in substitute
    return self.pattern.sub(convert, self.template)
  File "/usr/lib/python3.5/string.py", line 126, in convert
    self._invalid(mo)
  File "/usr/lib/python3.5/string.py", line 99, in _invalid
    (lineno, colno))
ValueError: Invalid placeholder in string: line 1, col 1
</pre>

This was working fine but has broken because of adding support for templated lxdock files, the thing is I don't see templated lxdock files as a very useful feature myself and the term "overengineering" comes to mind.  Lxdock should stay simple, this is going in the wrong direction making things too complex.

It seems I have to now escape every $ in my password strings:

e.g.

password: $6$Bm...

becomes

password: $$6$$Bm..

This is pretty silly, another solution might be to make templates stricter, e.g. only allow ${indentifier} but not $identifier, or switch to using Jinja2 and make it {{identifier}}

**Comment by robvdl** [comment]
I would suggest "can we revert variable substitution", but someone has asked for this feature, so reverting it now might not be the best.

I would therefore suggest, can we please switch to jinja2 instead of string.Template so that we are not getting unexpected substitutions.

**Comment by ellmetha** [comment]
@robvdl variable substitution allows the use of environment variables in LXDock files ; which can be useful when you're using the shell provisioner or if you want to dynamically insert some secret values at runtime (values that should not be committed into your LXDock file). This also has the benefit of easing the use provisioning tools that are not yet supported by LXDock (through the use of the shell provisioner).

That said, this functionality introduces a backward incompatible change that should be addressed of course. I don't think that changing the templating system for jinja2 would be a good solution. string.Template is a dead simple templating system. Jinja2 is not. With jinja2 you'd have if conditions, forloops, filters and template tags that you could use in your LXDock file... This very simple variable substitution system has been added to support environment variables / secret variables insertion into LXDock files ; it would be overkill to use jinja2 just for that.

Some possible solutions:

* changing the variable substitution syntax
* disabling variable substitution feature by default (would need an option to activate it)

**Comment by robvdl** [comment]
You could probably do your own substitution where you only allow ${var} but not $var which is the problematic one.

It would be really nice if you could turn of $var parsing without curly braces in string.Template(), but unfortunately it doesn't seem like you can looking at the docs.

So if Jinja2 is not an option, the only other thing I can think of is manually substituting ${var} and not using string.Template()

**Comment by robvdl** [comment]
@ellmetha: it looks like you can tweak String.template a bit: http://stackoverflow.com/questions/12768107/string-substitutions-using-templates-in-python (first answer which subclasses string.Template)

It should be possible to only allow ${var} but not $var and that would solve it.

I could have a go at it if you want, because it would be really great if this is resolved before 0.3 gets released.

**Comment by robvdl** [comment]
@ellmetha please check out pr #75 which subclasses string.Template to provide a stricter version which only supports ${var} but not $var which solves the issue without having to have an option to turn on/off variable substitution.

**Comment by ellmetha** [comment]
Fixed in 4999f96.
